[codecrate]
output = "context_codecrate.md"
keep_docstrings = true
dedupe = true
respect_gitignore = true
exclude = ["*/tests/*", "*/migrations/*", "*/.venv/*"]
include = ["**/*.py", "**/*.toml", "**/*.rst"]
split_max_chars = 250000
layout = "full"
